version: "3"
services:
    
    #フロントエンド
    frontend:
        container_name: frontend
        build: ./frontend
        tty: true
        stdin_open: true
        volumes:
            - type: bind
              source: ./frontend/app
              target: /frontend
        ports:
            - ${HOST_SERVER_PORT}:8080
    